### ISSUE TITLE
warn when there is a port conflict

### ISSUE THREAD

**Issue by josenildoamorim** [menezes-ssz/feature-express#10]
by default, feature-express uses port 3000. here in my project, we use port 3000 for another purpose (which I didn't knew at the moment). when I started the feature-express it indicated that it had started without problems, but it wasn't in the given link because the port was already in use.

the suggestion is that if the default port is already being used, feature-express indicates it and suggests using a different port

running on mac, node 8.11.1

thanks ! :)

**Comment by menezes-ssz** [comment]
Hi @josenildoamorim, feature-express use by default 3000 but you can send the port if you need!

Looks like this :

`$ feature-express ./YOUR-FEATURES-FOLDER/ pt 4444`

**Comment by leomenezessz** [comment]
alright, i will reproduce and check this @josenildoamorim, thks!

**Comment by leomenezessz** [comment]
warn for port conflict : https://github.com/menezes-ssz/feature-express/commit/2848116336dd7f1bbf945fe49de4742a7de1c007
