### ISSUE TITLE
Generate a static build

### ISSUE THREAD

**Issue by PabloAlexandre** [menezes-ssz/feature-express#15]
Hello!

I love Feature Express and I use so much in my projects. It's a graceful way to show the features and very helpful to shown for another people the test scenarios. One thing I missed is the option to generate a build folder with all static resources (html, css) to publish in a static server. The current way is good for local development or environment with nodeJS, but in some cases is more cheap to publish in a static server.

I can open this PR if you like this idea. I'll add an option in CLI to build and export all static resources in a folder that user will choise (Default option will be /build)

**Comment by leomenezessz** [comment]
Hello @PabloAlexandre!

I'am glad that feature express helps you! I understand what you need, but the feature-express is fully dynamic, you just need some automation like a cron or a pipeline to always get all your features files when you merge with your master branch. At same time i see a static build as a another exit for users and hope it helps a lot of people! 

I will wait for your pull request don't forget updatde readme and create unity tests if necessary!

Thanks!!
