### ISSUE TITLE
What is the minimum version of the node?

### ISSUE THREAD

**Issue by leonardovillela** [menezes-ssz/feature-express#8]
Hello Guys,

Cool project. I intend to contribute with the project by adding a Docker support, if you think it's a good idea, i can submit a PR? but for this it would be interesting to know the minimum version of the node that you intend to support.

**Comment by leomenezessz** [comment]
Hi @leonardovillela, feature-express works from version 6 onwards, every contribution are welcome, 
and I see the docker as a facilitator to run in different environments with simple commands. 
Thank you for your interest.

**Comment by leonardovillela** [comment]
Nice, i will use the latest version of LTS of node 6.x in Docker image. 

My planning for the Docker task:
- [x] Create Dockerfile with node 6.x LTS
- [ ] Add in CircleCI step to publish docker image in Dockerhub
- [ ] Update the docs with Docker usage info

What do you think? Anything left out?

**Comment by leonardovillela** [comment]
In the README.md says for any contribution to be made in the branch staging. But I noticed that the branch is outdated in relation to master. Can I do a git rebease from master on the staging branch to fix this?

**Comment by leomenezessz** [comment]
Oh sorry , @leonardovillela i think these tasks are good, about the staging branch yes, you can do a rebase with master please, thks again!
