### ISSUE TITLE
Use feature title instead of feature file name on the menu

### ISSUE THREAD

**Issue by josenildoamorim** [menezes-ssz/feature-express#9]
on the side menu, the names being displayed are those of the .feature files, which are not always written in a friendly way because they follow code standards (e.g. cameCase, snake_case...). I believe that, for a better understanding, it would be interesting to use the title that QA included in the feature file as a name.

thank you for this amazing tool :)

**Comment by leomenezessz** [comment]
In this fix #7  i removed the file extension name, in the next commit i will check the feature file name formatting. Thanks for suggestion @josenildoamorim!

**Comment by josenildoamorim** [comment]
thanks ! it will help me a lot to show scenarios to my users

**Comment by leomenezessz** [comment]
Change Title Format : https://github.com/menezes-ssz/feature-express/commit/008dacb09c9b053a89c48841e7d9c8b594d571b7
